language: php
php:
  - '5.6'
before_script:
  - cd ..
  - wget https://github.com/wikimedia/mediawiki/archive/1.25.3.tar.gz
  - tar -zxf 1.25.3.tar.gz
  - mv mediawiki-1.25.3 wiki
  - cd wiki
  - mv composer.json composer.json.bak
  - 'sed -n ''/"wikimedia\/composer-merge-plugin": "\^1\.3",/!p'' composer.json.bak > composer.json'
  - cat composer.json
  - rm composer.json.bak
  - mysql -e 'create database wiki;'
  - composer install --no-dev
  - php maintenance/install.php --dbtype mysql --dbuser root --dbname wiki --dbpath $TRAVIS_BUILD_DIR --pass nyan TravisWiki admin
  - composer require mediawiki/semantic-media-wiki "~2.3" --update-no-dev --quiet --no-interactions
  - php maintenance/update.php
  - echo "\nenableSemantics( 'example.org' )" >> LocalSettings.php
  - cd extensions
  - cp -r $TRAVIS_BUILD_DIR SphinxStore
  - cd ..
  - composer require 'phpunit/phpunit=3.7.*' --prefer-source
  - cd extensions/SemanticMediawiki
script:
  - composer phpunit

