language: php
php:
  - '5.6'
before_script:
  - phpenv config-rm xdebug.ini
  - apt-get install sphinxsearch
  - cd ..
  - wget https://github.com/wikimedia/mediawiki/archive/1.25.3.tar.gz
  - tar -zxf 1.25.3.tar.gz
  - mv mediawiki-1.25.3 wiki
  - cd wiki
  - mv composer.json composer.json.bak
  - 'sed -n ''/"wikimedia\/composer-merge-plugin": "1.0.0",/!p'' composer.json.bak > composer.json'
  - rm composer.json.bak
  - mysql -e 'create database wiki;'
  - composer install --no-dev
  - php maintenance/install.php --dbtype mysql --dbuser root --dbname wiki --dbpath $TRAVIS_BUILD_DIR --pass nyan TravisWiki admin
  - composer require 'mediawiki/semantic-media-wiki' "2.3.0" --update-no-dev --no-interaction
  - composer require 'foolz/sphinxql-query-builder=1.1.0' --no-interaction --prefer-source
  - composer require 'mediawiki/semantic-forms=3.2' --no-interaction --prefer-source
  - composer require 'phpunit/phpunit=3.7.37' --prefer-source --no-interaction
  - composer update
  - echo -e "\nenableSemantics( 'example.org' );\n" >> LocalSettings.php
  - cd extensions
  - cp -r $TRAVIS_BUILD_DIR SphinxStore
  - cp SphinxStore/config/sphinx.conf /etc/sphinxsearch/sphinx.conf
  - cd ..
  #- echo -e "\nwfLoadExtension('SphinxStore');\n" >> LocalSettings.php
  - php maintenance/update.php --quick
  - cd extensions/SemanticMediaWiki
script:
  - composer phpunit
  #- cd ../SphinxStore
  #- composer phpunit